services:
  - type: web
    name: marvel-champions-bgg-stats
    runtime: static
    buildCommand: chmod +x build.sh && ./build.sh
    staticPublishPath: .
    domains:
      - marvel-champions-bgg-stats.onrender.com
    envVars:
      - key: NODE_ENV
        value: production
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /favicon.ico
        name: Cache-Control
        value: public, max-age=86400
      - path: /*.css
        name: Cache-Control
        value: public, max-age=31536000
      - path: /*.js
        name: Cache-Control
        value: public, max-age=31536000
      - path: /*.json
        name: Cache-Control
        value: public, max-age=3600
      - path: /*.png
        name: Cache-Control
        value: public, max-age=31536000
      - path: /*.jpg
        name: Cache-Control
        value: public, max-age=31536000
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
